-- Question #3: 
-- Your manager wants to compare the sales performance and the average number of days since the client was last updated
-- between the long term customers and all other customers.

-- What is the total revenue generated by Meta in 2022 and the average number of days since the client information was 
-- last updated for clients with a client ID with a number between 0 and 1000 versus all the other clients?


		SELECT 
    			CASE 
          		WHEN client_id_num BETWEEN 0 AND 100 THEN 'Long Term CLients'
              ELSE 'Other Clients'
          END AS client_group,
          SUM(revenue) AS total_revenue,
          AVG(diff_date) AS last_update_avg_days_since_update

			FROM
							(
        SELECT         
							CURRENT_DATE - meta_clients.last_updated_date AS diff_date,
      				(meta_revenue.revenue) AS revenue,
              EXTRACT(YEAR FROM meta_revenue.dates) AS years,

    					CAST(SUBSTRING(meta_clients.client_id,8,100) AS INTEGER) AS client_id_num
              
								FROM meta_clients
           			LEFT JOIN meta_revenue ON meta_clients.client_id = meta_revenue.client_id
                              
              GROUP BY client_id_num ,revenue ,years,diff_date
          	) 
          AS subquery
          WHERE 
          years = 2022 
          GROUP BY client_group
          